blueprint:
  name: Allarme per fumo
  description: Vengono inviate una notifica push su Telegram e una notifica persistente ad Home Assistant non appena uno dei sensori individua del fumo.
  domain: automation
  homeassistant:
    min_version: 2022.11.0
  source_url: https://github.com/Morriz1971/HomeAssistant-Blueprints/blob/main/allarme_fumo.yaml
  input:
    title:
        name: Titolo
        description: Titolo della notifica da inviare per es. Allarme fuoco
        default: 'HA PIEVE - Allarme fumo'
        selector:
            text:

    text:
        name: Messaggio
        description: Testo del messaggio. Questo messaggio viene aggiunto al nome del sensore [sensor name] [text message].
        default: ATTENZIONE! È stato rilevato del **fumo nella tavernetta** alle {{ states('sensor.time') }} di {{ states('sensor.time_formatted') }}.
        selector:
            text:

trigger:
  platform: template
  value_template: "{{ states.binary_sensor | selectattr('attributes.device_class', 'eq', 'smoke') | map(attribute='state') | list | join(',') == 'on' }}"

variables:
    text_var: !input text
    
action:
  - service: telegram_bot.send_message
    data:
      title: !input title
      parse_mode: markdown
      message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} {{ text_var }}"
  - service: notify.persistent_notification
    data:
        title: !input title
        parse_mode: markdown
        message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} {{ text_var }}"
mode: single
